spring.application.name=Taskmgmt

server.servlet.context-path =/api

#spring.datasource.url=jdbc:postgresql://localhost:5432/task_mgmt
#spring.datasource.username=postgres
#spring.datasource.password=0000
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.data.jdbc.repositories.enabled=false
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework=DEBUG
#logging.level.com.telusko=DEBUG

#
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect




