FROM eclipse-temurin:17-jdk

WORKDIR /app

# Copy maven wrapper and pom
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

RUN chmod +x mvnw
RUN ./mvnw dependency:go-offline

# Copy source code
COPY src src

EXPOSE 8080

# Run Spring Boot in DEV mode
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]
